In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [3]:
df=pd.read_csv('leetcode_3400_problems_dataset.csv')

In [26]:
df['Topic_Tags'].unique()

array(['Array, Hash Table', 'Linked List, Math, Recursion',
       'Hash Table, String, Sliding Window', ...,
       'Bit Manipulation, Greedy, Topological Sort',
       'Recursion, Topological Sort', 'Tree, Binary Search, Recursion'],
      dtype=object)

In [5]:
tags_series = df['Topic_Tags'].fillna('').apply(
    lambda x: [t.strip() for t in x.split(',') if t.strip()]
)
dummies = pd.get_dummies(tags_series.explode()).groupby(level=0).sum()
dummies = (dummies > 0).astype(int)  

df_topic = pd.concat([df, dummies], axis=1)

In [27]:
df_topic

,Problem_ID,Problem_Name,Topic_Tags,Difficulty,Time_Beginner_Mins,Time_Average_Mins,Time_Expert_Mins,Array,Backtracking,Binary Search,...,Sliding Window,Sorting,Stack,String,String Matching,Topological Sort,Tree,Trie,Two Pointers,Union Find
0,1,Two Sum,"Array, Hash Table",Easy,25,12,5,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Add Two Numbers,"Linked List, Math, Recursion",Medium,55,28,12,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,Longest Substring Without Repeating Characters,"Hash Table, String, Sliding Window",Medium,55,28,12,0,0,0,...,1,0,0,1,0,0,0,0,0,0
3,4,Median of Two Sorted Arrays,"Array, Binary Search, Divide and Conquer",Hard,110,55,22,1,0,1,...,0,0,0,0,0,0,0,0,0,0
4,5,Longest Palindromic Substring,"String, Dynamic Programming",Medium,55,28,12,0,0,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3395,3396,LeetCode Problem 3396,"Recursion, Topological Sort",Easy,25,16,5,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3396,3397,LeetCode Problem 3397,"Tree, Binary Search, Recursion",Hard,134,76,34,0,0,1,...,0,0,0,0,0,0,1,0,0,0
3397,3398,LeetCode Problem 3398,"Prefix Sum, Sorting",Medium,52,30,16,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3398,3399,LeetCode Problem 3399,"Stack, Sorting",Medium,60,31,16,0,0,0,...,0,1,1,0,0,0,0,0,0,0
3399,3400,LeetCode Problem 3400,"Breadth-First Search, Tree",Easy,24,12,4,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [7]:
df_topic_diff=pd.get_dummies(df_topic,columns=['Difficulty'],dtype=int)

In [ ]:
df_topic_diff

In [9]:
df_topic_diff_filtercol=df_topic_diff.drop(columns=['Topic_Tags','Problem_Name','Problem_ID'])

In [ ]:
df_topic_diff_filtercol

In [10]:
df_topic_diff_filtercol_beg=df_topic_diff_filtercol.drop(columns=['Time_Average_Mins','Time_Expert_Mins'])
df_topic_diff_filtercol_med=df_topic_diff_filtercol.drop(columns=['Time_Expert_Mins','Time_Beginner_Mins'])
df_topic_diff_filtercol_exp=df_topic_diff_filtercol.drop(columns=['Time_Beginner_Mins','Time_Average_Mins'])

In [24]:
df_topic_diff_filtercol_beg

,Time_Beginner_Mins,Array,Backtracking,Binary Search,Binary Search Tree,Binary Tree,Bit Manipulation,Breadth-First Search,Combinatorics,Database,...,String,String Matching,Topological Sort,Tree,Trie,Two Pointers,Union Find,Difficulty_Easy,Difficulty_Hard,Difficulty_Medium
0,25,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,55,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,55,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
3,110,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,55,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3395,25,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
3396,134,0,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
3397,52,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3398,60,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3399,24,0,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,1,0,0

In [11]:
Y=df_topic_diff_filtercol_beg['Time_Beginner_Mins']

In [12]:
X=df_topic_diff_filtercol_beg.drop(columns=['Time_Beginner_Mins'])

In [13]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42,shuffle=True)

In [14]:
model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)

In [15]:
model.fit(X_train,Y_train)

RandomForestRegressor(n_jobs=-1, random_state=42)

In [16]:
Y_pred=model.predict(X_test)

In [17]:
mae = mean_absolute_error(Y_test, Y_pred)
mse = mean_squared_error(Y_test, Y_pred)
r2 = r2_score(Y_test, Y_pred)

In [18]:
mae

9.589918933991246

In [19]:
mse

169.7205018024446

In [41]:
r2

0.8643286279169834

In [53]:
df_data=pd.read_csv("striverSheet.csv")

In [54]:
df_data.head(100)

,Step,Category,Problem Name,Problem Link,Primary Topic,LeetCode Topics,Difficulty,Acceptance Rate (%),Time (Beginner) [min],Time (Medium) [min],Time (Expert) [min]
0,Step 1,Learn the Basics,User Input / Output in C++ / Java / Python,https://www.geeksforgeeks.org/c-input-output/,Basic I/O,"Math, Number Theory",Easy,85,10,3,1
1,Step 1,Learn the Basics,Data Types,https://www.geeksforgeeks.org/c-data-types/,Basics,"Math, Number Theory",Easy,82,10,3,1
2,Step 1,Learn the Basics,If Else Statements,https://www.geeksforgeeks.org/decision-making-...,Control Flow,"Math, Number Theory",Easy,88,10,3,1
3,Step 1,Learn the Basics,Switch Statement,https://www.geeksforgeeks.org/switch-statement...,Control Flow,"Math, Number Theory",Easy,85,10,3,1
4,Step 1,Learn the Basics,For Loops & While Loops,https://www.geeksforgeeks.org/loops-in-c/,Loops,"Math, Number Theory",Easy,80,12,4,2
...,...,...,...,...,...,...,...,...,...,...,...
95,Step 4,Binary Search,Split Array - Largest Sum,https://leetcode.com/problems/split-array---la...,BS Answers,"Array, Binary Search",Hard,54,65,28,11
96,Step 4,Binary Search,Painter's Partition Problem,https://leetcode.com/problems/painters-partiti...,BS Answers,"Array, Binary Search",Hard,48,65,28,11
97,Step 4,Binary Search,Minimize Max Distance to Gas Station,https://leetcode.com/problems/minimize-max-dis...,BS Answers,"Array, Binary Search",Hard,38,80,35,14
98,Step 4,Binary Search,Median of 2 Sorted Arrays,https://leetcode.com/problems/median-of-2-sort...,BS Answers,"Array, Binary Search, Divide and Conquer",Hard,38,75,32,13
99,Step 4,Binary Search,K-th Element of Two Sorted Arrays,https://leetcode.com/problems/k-th-element-of-...,BS Answers,"Array, Binary Search",Medium,50,50,22,9

In [55]:
df_data_filter=df_data[(df_data['Category']=="Binary Search") & (df_data['Difficulty']=="Medium")]

In [56]:
df_data_filter

,Step,Category,Problem Name,Problem Link,Primary Topic,LeetCode Topics,Difficulty,Acceptance Rate (%),Time (Beginner) [min],Time (Medium) [min],Time (Expert) [min]
78,Step 4,Binary Search,First and Last Occurrence in Array,https://leetcode.com/problems/first-and-last-o...,BS 1D,"Array, Binary Search",Medium,42,25,10,4
79,Step 4,Binary Search,Count Occurrences in Sorted Array,https://leetcode.com/problems/count-occurrence...,BS 1D,"Array, Binary Search",Medium,58,25,10,4
80,Step 4,Binary Search,Search in Rotated Sorted Array I,https://leetcode.com/problems/search-in-rotate...,BS 1D,"Array, Binary Search",Medium,40,40,15,6
81,Step 4,Binary Search,Search in Rotated Sorted Array II (Duplicates),https://leetcode.com/problems/search-in-rotate...,BS 1D,"Array, Binary Search",Medium,36,45,18,7
82,Step 4,Binary Search,Find Minimum in Rotated Sorted Array,https://leetcode.com/problems/find-minimum-in-...,BS 1D,"Array, Binary Search",Medium,52,35,14,5
83,Step 4,Binary Search,Find out how many times array is rotated,https://leetcode.com/problems/find-out-how-man...,BS 1D,"Array, Binary Search",Medium,50,30,12,5
84,Step 4,Binary Search,Single Element in Sorted Array,https://leetcode.com/problems/single-element-i...,BS 1D,"Array, Binary Search",Medium,59,35,15,6
85,Step 4,Binary Search,Find Peak Element,https://leetcode.com/problems/find-peak-element/,BS 1D,"Array, Binary Search",Medium,47,35,15,6
87,Step 4,Binary Search,Find Nth Root of M,https://leetcode.com/problems/find-nth-root-of-m/,BS Answers,"Array, Binary Search",Medium,42,30,12,5
88,Step 4,Binary Search,Koko Eating Bananas,https://leetcode.com/problems/koko-eating-bana...,BS Answers,"Array, Binary Search",Medium,51,45,18,7
89,Step 4,Binary Search,Minimum days to make M bouquets,https://leetcode.com/problems/minimum-days-to-...,BS Answers,"Array, Binary Search",Medium,54,45,18,7
90,Step 4,Binary Search,Find the Smallest Divisor Given a Threshold,https://leetcode.com/problems/find-the-smalles...,BS Answers,"Array, Binary Search",Medium,57,45,18,7
91,Step 4,Binary Search,Capacity to Ship Packages Within D Days,https://leetcode.com/problems/capacity-to-ship...,BS Answers,"Array, Binary Search",Medium,68,45,18,7
99,Step 4,Binary Search,K-th Element of Two Sorted Arrays,https://leetcode.com/problems/k-th-element-of-...,BS Answers,"Array, Binary Search",Medium,50,50,22,9
100,Step 4,Binary Search,Search in 2D Matrix I,https://leetcode.com/problems/search-in-2d-mat...,BS 2D,"Array, Binary Search",Medium,49,35,14,5
101,Step 4,Binary Search,Search in 2D Matrix II,https://leetcode.com/problems/search-in-2d-mat...,BS 2D,"Array, Binary Search",Medium,51,35,14,5

In [71]:
random_row=df_data_filter.sample(n=1)

In [72]:
random_row

,Step,Category,Problem Name,Problem Link,Primary Topic,LeetCode Topics,Difficulty,Acceptance Rate (%),Time (Beginner) [min],Time (Medium) [min],Time (Expert) [min]
79,Step 4,Binary Search,Count Occurrences in Sorted Array,https://leetcode.com/problems/count-occurrence...,BS 1D,"Array, Binary Search",Medium,58,25,10,4

In [73]:
tags_series = random_row['LeetCode Topics'].fillna('').apply(
    lambda x: [t.strip() for t in x.split(',') if t.strip()]
)
dummies = pd.get_dummies(tags_series.explode()).groupby(level=0).sum()
dummies = (dummies > 0).astype(int)  

random_row = pd.concat([random_row, dummies], axis=1)

In [74]:
random_row

,Step,Category,Problem Name,Problem Link,Primary Topic,LeetCode Topics,Difficulty,Acceptance Rate (%),Time (Beginner) [min],Time (Medium) [min],Time (Expert) [min],Array,Binary Search
79,Step 4,Binary Search,Count Occurrences in Sorted Array,https://leetcode.com/problems/count-occurrence...,BS 1D,"Array, Binary Search",Medium,58,25,10,4,1,1