In [75]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from leetcode_scraper import LeetcodeScraper

ModuleNotFoundError: No module named 'leetcode_scraper'

In [3]:
df=pd.read_csv('leetcode_3400_problems_dataset.csv')

In [26]:
df['Topic_Tags'].unique()

array(['Array, Hash Table', 'Linked List, Math, Recursion',
       'Hash Table, String, Sliding Window', ...,
       'Bit Manipulation, Greedy, Topological Sort',
       'Recursion, Topological Sort', 'Tree, Binary Search, Recursion'],
      dtype=object)

In [5]:
tags_series = df['Topic_Tags'].fillna('').apply(
    lambda x: [t.strip() for t in x.split(',') if t.strip()]
)
dummies = pd.get_dummies(tags_series.explode()).groupby(level=0).sum()
dummies = (dummies > 0).astype(int)  

df_topic = pd.concat([df, dummies], axis=1)

In [27]:
df_topic

,Problem_ID,Problem_Name,Topic_Tags,Difficulty,Time_Beginner_Mins,Time_Average_Mins,Time_Expert_Mins,Array,Backtracking,Binary Search,...,Sliding Window,Sorting,Stack,String,String Matching,Topological Sort,Tree,Trie,Two Pointers,Union Find
0,1,Two Sum,"Array, Hash Table",Easy,25,12,5,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Add Two Numbers,"Linked List, Math, Recursion",Medium,55,28,12,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,Longest Substring Without Repeating Characters,"Hash Table, String, Sliding Window",Medium,55,28,12,0,0,0,...,1,0,0,1,0,0,0,0,0,0
3,4,Median of Two Sorted Arrays,"Array, Binary Search, Divide and Conquer",Hard,110,55,22,1,0,1,...,0,0,0,0,0,0,0,0,0,0
4,5,Longest Palindromic Substring,"String, Dynamic Programming",Medium,55,28,12,0,0,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3395,3396,LeetCode Problem 3396,"Recursion, Topological Sort",Easy,25,16,5,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3396,3397,LeetCode Problem 3397,"Tree, Binary Search, Recursion",Hard,134,76,34,0,0,1,...,0,0,0,0,0,0,1,0,0,0
3397,3398,LeetCode Problem 3398,"Prefix Sum, Sorting",Medium,52,30,16,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3398,3399,LeetCode Problem 3399,"Stack, Sorting",Medium,60,31,16,0,0,0,...,0,1,1,0,0,0,0,0,0,0
3399,3400,LeetCode Problem 3400,"Breadth-First Search, Tree",Easy,24,12,4,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [7]:
df_topic_diff=pd.get_dummies(df_topic,columns=['Difficulty'],dtype=int)

In [ ]:
df_topic_diff

In [9]:
df_topic_diff_filtercol=df_topic_diff.drop(columns=['Topic_Tags','Problem_Name','Problem_ID'])

In [ ]:
df_topic_diff_filtercol

In [10]:
df_topic_diff_filtercol_beg=df_topic_diff_filtercol.drop(columns=['Time_Average_Mins','Time_Expert_Mins'])
df_topic_diff_filtercol_med=df_topic_diff_filtercol.drop(columns=['Time_Expert_Mins','Time_Beginner_Mins'])
df_topic_diff_filtercol_exp=df_topic_diff_filtercol.drop(columns=['Time_Beginner_Mins','Time_Average_Mins'])

In [24]:
df_topic_diff_filtercol_beg

,Time_Beginner_Mins,Array,Backtracking,Binary Search,Binary Search Tree,Binary Tree,Bit Manipulation,Breadth-First Search,Combinatorics,Database,...,String,String Matching,Topological Sort,Tree,Trie,Two Pointers,Union Find,Difficulty_Easy,Difficulty_Hard,Difficulty_Medium
0,25,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,55,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,55,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
3,110,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,55,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3395,25,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
3396,134,0,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
3397,52,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3398,60,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3399,24,0,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,1,0,0

In [11]:
Y=df_topic_diff_filtercol_beg['Time_Beginner_Mins']

In [12]:
X=df_topic_diff_filtercol_beg.drop(columns=['Time_Beginner_Mins'])

In [13]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42,shuffle=True)

In [14]:
model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)

In [15]:
model.fit(X_train,Y_train)

RandomForestRegressor(n_jobs=-1, random_state=42)

In [16]:
Y_pred=model.predict(X_test)

In [17]:
mae = mean_absolute_error(Y_test, Y_pred)
mse = mean_squared_error(Y_test, Y_pred)
r2 = r2_score(Y_test, Y_pred)

In [18]:
mae

9.589918933991246

In [19]:
mse

169.7205018024446

In [41]:
r2

0.8643286279169834

In [77]:
df_data=pd.read_csv("striver_a2z_beginner_formatted.csv")

In [81]:
df_data.head(100)

,Problem name,Multi topic tags,Difficulty,Leetcode(more priority)/geeks for geeks link of corresponding problem
0,User Input / Output,"Basics, Input-Output",Easy,https://www.geeksforgeeks.org/problems/input-o...
1,Data Types,"Basics, Data Types",Easy,https://www.geeksforgeeks.org/problems/data-ty...
2,If Else statements,"Basics, Conditionals",Easy,https://www.geeksforgeeks.org/problems/java-if...
3,Switch Statement,"Basics, Conditionals",Easy,https://www.geeksforgeeks.org/problems/java-sw...
4,Find Pattern 1 to 22,"Basics, Patterns, Loops",Easy,https://takeuforward.org/strivers-a2z-dsa-cour...
...,...,...,...,...
95,Middle of Linked List,"Linked List, Two Pointers",Easy,https://leetcode.com/problems/middle-of-the-li...
96,Detect Loop in Linked List,"Linked List, Two Pointers, Hash Table",Easy,https://leetcode.com/problems/linked-list-cycle/
97,Find Starting Point of Loop in Linked List,"Linked List, Two Pointers, Hash Table",Medium,https://leetcode.com/problems/linked-list-cycl...
98,Length of Loop in Linked List,"Linked List, Two Pointers",Easy,https://www.geeksforgeeks.org/problems/find-le...
99,Check if Linked List is Palindrome,"Linked List, Two Pointers, Recursion",Easy,https://leetcode.com/problems/palindrome-linke...

In [88]:
df_data.rename(columns={'Leetcode(more priority)/geeks for geeks link of corresponding problem':'Link'},inplace=True)

In [90]:
df_data['Difficulty'].unique()

array(['Easy', 'Medium'], dtype=object)

In [89]:
df_data

,Problem name,Multi topic tags,Difficulty,Link
0,User Input / Output,"Basics, Input-Output",Easy,https://www.geeksforgeeks.org/problems/input-o...
1,Data Types,"Basics, Data Types",Easy,https://www.geeksforgeeks.org/problems/data-ty...
2,If Else statements,"Basics, Conditionals",Easy,https://www.geeksforgeeks.org/problems/java-if...
3,Switch Statement,"Basics, Conditionals",Easy,https://www.geeksforgeeks.org/problems/java-sw...
4,Find Pattern 1 to 22,"Basics, Patterns, Loops",Easy,https://takeuforward.org/strivers-a2z-dsa-cour...
...,...,...,...,...
138,Longest Common Subsequence,"Dynamic Programming, Strings",Medium,https://leetcode.com/problems/longest-common-s...
139,Longest Increasing Subsequence,"Dynamic Programming, Binary Search",Medium,https://leetcode.com/problems/longest-increasi...
140,Partition Array for Maximum Sum,"Dynamic Programming, Arrays",Medium,https://leetcode.com/problems/partition-array-...
141,Longest String with All Prefixes,"Trie, Strings",Medium,https://www.geeksforgeeks.org/problems/longest...
142,Number of Distinct Substrings in a String,"Trie, Strings",Medium,https://www.geeksforgeeks.org/problems/count-o...

In [86]:
df_data_problem=df_data['Problem name']
df_data_link=df_data['Difficulty']

In [84]:
df_data_problem

0                            User Input / Output
1                                     Data Types
2                             If Else statements
3                               Switch Statement
4                           Find Pattern 1 to 22
                         ...
138                   Longest Common Subsequence
139               Longest Increasing Subsequence
140              Partition Array for Maximum Sum
141             Longest String with All Prefixes
142    Number of Distinct Substrings in a String
Name: Problem name, Length: 143, dtype: object

In [71]:
random_row=df_data_filter.sample(n=1)

In [72]:
random_row

,Step,Category,Problem Name,Problem Link,Primary Topic,LeetCode Topics,Difficulty,Acceptance Rate (%),Time (Beginner) [min],Time (Medium) [min],Time (Expert) [min]
79,Step 4,Binary Search,Count Occurrences in Sorted Array,https://leetcode.com/problems/count-occurrence...,BS 1D,"Array, Binary Search",Medium,58,25,10,4

In [73]:
tags_series = random_row['LeetCode Topics'].fillna('').apply(
    lambda x: [t.strip() for t in x.split(',') if t.strip()]
)
dummies = pd.get_dummies(tags_series.explode()).groupby(level=0).sum()
dummies = (dummies > 0).astype(int)  

random_row = pd.concat([random_row, dummies], axis=1)

In [74]:
random_row

,Step,Category,Problem Name,Problem Link,Primary Topic,LeetCode Topics,Difficulty,Acceptance Rate (%),Time (Beginner) [min],Time (Medium) [min],Time (Expert) [min],Array,Binary Search
79,Step 4,Binary Search,Count Occurrences in Sorted Array,https://leetcode.com/problems/count-occurrence...,BS 1D,"Array, Binary Search",Medium,58,25,10,4,1,1