In [38]:
import pandas as pd
import numpy as np
import seaborn as sns

In [39]:
data_df=pd.read_csv('TEMP_ANNUAL_MEAN_1901-2021.csv')
data_df.head()

,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,JAN-FEB,MAR-MAY,JUN-SEP,OCT-DEC
0,1901.0,19.32,20.89,24.95,28.22,29.76,29.85,28.24,27.33,27.23,26.33,22.92,20.05,25.42,20.11,27.64,28.16,23.10
1,1902.0,20.17,21.58,25.73,28.15,30.00,29.47,27.99,27.71,26.76,25.33,22.43,19.77,25.42,20.88,27.96,27.98,22.51
2,1903.0,19.28,20.71,23.92,27.67,29.47,29.53,28.32,27.16,27.00,25.69,22.01,19.30,25.01,19.99,27.02,28.00,22.33
3,1904.0,19.19,20.32,24.41,28.11,29.17,28.80,27.36,27.26,26.84,25.67,22.16,19.86,24.93,19.76,27.23,27.57,22.56
4,1905.0,18.34,18.37,23.15,26.26,29.73,29.87,28.13,27.65,27.16,26.35,23.24,19.79,24.84,18.36,26.38,28.20,23.13

In [49]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   YEAR     121 non-null    float64
 1   JAN      123 non-null    object
 2   FEB      123 non-null    object
 3   MAR      123 non-null    object
 4   APR      123 non-null    object
 5   MAY      123 non-null    object
 6   JUN      123 non-null    object
 7   JUL      123 non-null    object
 8   AUG      123 non-null    object
 9   SEP      123 non-null    object
 10  OCT      123 non-null    object
 11  NOV      123 non-null    object
 12  DEC      123 non-null    object
 13  ANNUAL   123 non-null    object
 14  JAN-FEB  123 non-null    object
 15  MAR-MAY  123 non-null    object
 16  JUN-SEP  123 non-null    object
 17  OCT-DEC  123 non-null    object
dtypes: float64(1), object(17)
memory usage: 17.7+ KB

In [51]:
data_df.describe()

              YEAR
count   121.000000
mean   1961.000000
std      35.073732
min    1901.000000
25%    1931.000000
50%    1961.000000
75%    1991.000000
max    2021.000000

In [ ]:
data_df['YEAR']=data_df['YEAR'].fillna

np.int64(4)

In [44]:
# data_df['ANNUAL'].isnull().sum()
#type(data_df['ANNUAL'].loc[0])
data_df["ANNUAL"] = data_df["ANNUAL"].astype(float)
# 122    NaN
# 123    NaN
#data_df['ANNUAL']=data_df['ANNUAL'].fillna(data_df['ANNUAL'].mean())
#data_df['ANNUAL'] = pd.to_numeric(data_df['ANNUAL'], errors='coerce')
#data_df['ANNUAL'] = data_df['ANNUAL'].fillna(data_df['ANNUAL'].mean())

ValueError: could not convert string to float: 'ANNUAL'

In [ ]:
# data_df[data_df["ANNUAL"] == "ANNUAL"]

,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,JAN-FEB,MAR-MAY,JUN-SEP,OCT-DEC
121,NaN,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,JAN-FEB,MAR-MAY,JUN-SEP,OCT-DEC