In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('TEMP_ANNUAL_MEAN_1901-2021.csv')

In [5]:
type(TEMP_ANNUAL_MEAN_1901-2021.csv)

SyntaxError: invalid decimal literal (648507483.py, line 1)

In [4]:
df.head()

,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,JAN-FEB,MAR-MAY,JUN-SEP,OCT-DEC
0,1901.0,19.32,20.89,24.95,28.22,29.76,29.85,28.24,27.33,27.23,26.33,22.92,20.05,25.42,20.11,27.64,28.16,23.10
1,1902.0,20.17,21.58,25.73,28.15,30.00,29.47,27.99,27.71,26.76,25.33,22.43,19.77,25.42,20.88,27.96,27.98,22.51
2,1903.0,19.28,20.71,23.92,27.67,29.47,29.53,28.32,27.16,27.00,25.69,22.01,19.30,25.01,19.99,27.02,28.00,22.33
3,1904.0,19.19,20.32,24.41,28.11,29.17,28.80,27.36,27.26,26.84,25.67,22.16,19.86,24.93,19.76,27.23,27.57,22.56
4,1905.0,18.34,18.37,23.15,26.26,29.73,29.87,28.13,27.65,27.16,26.35,23.24,19.79,24.84,18.36,26.38,28.20,23.13

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   YEAR     121 non-null    float64
 1   JAN      123 non-null    object
 2   FEB      123 non-null    object
 3   MAR      123 non-null    object
 4   APR      123 non-null    object
 5   MAY      123 non-null    object
 6   JUN      123 non-null    object
 7   JUL      123 non-null    object
 8   AUG      123 non-null    object
 9   SEP      123 non-null    object
 10  OCT      123 non-null    object
 11  NOV      123 non-null    object
 12  DEC      123 non-null    object
 13  ANNUAL   123 non-null    object
 14  JAN-FEB  123 non-null    object
 15  MAR-MAY  123 non-null    object
 16  JUN-SEP  123 non-null    object
 17  OCT-DEC  123 non-null    object
dtypes: float64(1), object(17)
memory usage: 17.7+ KB

In [6]:
df.describe()

              YEAR
count   121.000000
mean   1961.000000
std      35.073732
min    1901.000000
25%    1931.000000
50%    1961.000000
75%    1991.000000
max    2021.000000

In [7]:
df.isnull().sum()

YEAR       4
JAN        2
FEB        2
MAR        2
APR        2
MAY        2
JUN        2
JUL        2
AUG        2
SEP        2
OCT        2
NOV        2
DEC        2
ANNUAL     2
JAN-FEB    2
MAR-MAY    2
JUN-SEP    2
OCT-DEC    2
dtype: int64

In [25]:
columns=df.columns.to_list()

In [26]:
# for feature in columns:
#     df[feature]=pd.to_numeric(df[feature],errors='coerce')
df[columns] = df[columns].apply(pd.to_numeric, errors='coerce')

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   YEAR     121 non-null    float64
 1   JAN      122 non-null    float64
 2   FEB      122 non-null    float64
 3   MAR      122 non-null    float64
 4   APR      122 non-null    float64
 5   MAY      122 non-null    float64
 6   JUN      122 non-null    float64
 7   JUL      122 non-null    float64
 8   AUG      122 non-null    float64
 9   SEP      122 non-null    float64
 10  OCT      122 non-null    float64
 11  NOV      122 non-null    float64
 12  DEC      122 non-null    float64
 13  ANNUAL   122 non-null    float64
 14  JAN-FEB  122 non-null    float64
 15  MAR-MAY  122 non-null    float64
 16  JUN-SEP  122 non-null    float64
 17  OCT-DEC  122 non-null    float64
dtypes: float64(18)
memory usage: 17.7 KB

In [ ]:
# columns1 = df.columns.drop(['YEAR','JAN'])

In [28]:
df.loc[df['YEAR'].isnull()]

,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,JAN-FEB,MAR-MAY,JUN-SEP,OCT-DEC
121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,NaN,24.99,28.0386,30.4741,33.9128,35.2268,33.4088,32.3118,31.5344,31.9751,32.0322,29.1711,26.5851,30.805,26.5141,33.2046,32.3075,29.2628

In [37]:
df.shape

(125, 18)

In [54]:
df=df.drop(index=[122,123])

In [55]:
df.shape

(122, 18)

In [56]:
df.loc[df['YEAR'].isnull()]

,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,JAN-FEB,MAR-MAY,JUN-SEP,OCT-DEC
124,NaN,24.99,28.0386,30.4741,33.9128,35.2268,33.4088,32.3118,31.5344,31.9751,32.0322,29.1711,26.5851,30.805,26.5141,33.2046,32.3075,29.2628

In [58]:
df

,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,JAN-FEB,MAR-MAY,JUN-SEP,OCT-DEC
0,1901.0,19.32,20.8900,24.9500,28.2200,29.7600,29.8500,28.2400,27.3300,27.2300,26.3300,22.9200,20.0500,25.420,20.1100,27.6400,28.1600,23.1000
1,1902.0,20.17,21.5800,25.7300,28.1500,30.0000,29.4700,27.9900,27.7100,26.7600,25.3300,22.4300,19.7700,25.420,20.8800,27.9600,27.9800,22.5100
2,1903.0,19.28,20.7100,23.9200,27.6700,29.4700,29.5300,28.3200,27.1600,27.0000,25.6900,22.0100,19.3000,25.010,19.9900,27.0200,28.0000,22.3300
3,1904.0,19.19,20.3200,24.4100,28.1100,29.1700,28.8000,27.3600,27.2600,26.8400,25.6700,22.1600,19.8600,24.930,19.7600,27.2300,27.5700,22.5600
4,1905.0,18.34,18.3700,23.1500,26.2600,29.7300,29.8700,28.1300,27.6500,27.1600,26.3500,23.2400,19.7900,24.840,18.3600,26.3800,28.2000,23.1300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,2018.0,19.90,22.5800,26.0100,28.4800,29.9900,29.5800,28.1900,27.7300,27.6300,26.4200,23.8400,20.4100,25.900,21.2400,28.1600,28.2800,23.5500
118,2019.0,19.62,21.8000,24.9200,28.8200,30.2700,30.2600,28.6500,27.9200,27.5600,26.2200,23.9300,20.3200,25.860,20.7100,28.0000,28.6000,23.4900
119,2020.0,19.65,21.9300,24.7600,28.1400,29.8400,29.1100,28.5400,28.1300,28.0300,26.9600,23.4800,20.8200,25.780,20.7900,27.5800,28.4500,23.7500
120,2021.0,20.31,22.5500,26.3000,28.4200,29.1700,29.0700,28.5200,28.0700,27.7900,26.7900,23.4700,20.7200,25.930,21.4300,27.9700,28.3600,23.6600
124,NaN,24.99,28.0386,30.4741,33.9128,35.2268,33.4088,32.3118,31.5344,31.9751,32.0322,29.1711,26.5851,30.805,26.5141,33.2046,32.3075,29.2628